version: '3'
services:
  smtp:
    image: namshi/smtp
    container_name: project.smtp
    restart: always
    ports:
     - "2525:2525"
    environment:
     # # MUST start with : e.g RELAY_NETWORKS=:192.168.0.0/24:10.0.0.0/16
     # # if acting as a relay this or RELAY_DOMAINS must be filled out or incoming mail will be rejected
     # 轉發用的方案
     # - RELAY_NETWORKS= :192.168.0.0/24
     # # what domains should be accepted to forward to lower distance MX server.
     # - RELAY_DOMAINS= <domain1> : <domain2> : <domain3>
     # # To act as a Gmail relay
     # - GMAIL_USER=
     # - GMAIL_PASSWORD=
     # # For use with Amazon SES relay
     # - SES_USER=
     # - SES_PASSWORD=
     # - SES_REGION=
     # # if provided will enable TLS support
     # - KEY_PATH=
     # - CERTIFICATE_PATH=
     # # the outgoing mail hostname
     # - MAILNAME=
     # # set this to any value to disable ipv6
     - DISABLE_IPV6=true
     # # Generic SMTP Relay
     # - SMARTHOST_ADDRESS=fruit.mail.tpigame.com
     # - SMARTHOST_PORT=2525
     # - SMARTHOST_USER=fruit
     # - SMARTHOST_PASSWORD=happy_time
     # - SMARTHOST_ALIASES=*.tpigame.com
